debug: false

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful
  forward-headers-strategy: framework
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

logging:
  level:
    root: INFO
    org.springframework.web: WARN
